(define (call-the-cops) (display "UIU UIU"))
(define (make-account balance acc-pass)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define failted-attempts-count 0)
  (define (incFailedAttempts)
    (set! failted-attempts-count (+ 1 failted-attempts-count))
    failted-attempts-count)
  (define (dispatch m password)
    (cond ((not (equal? acc-pass password)) (if (= 3 (incFailedAttempts)) (call-the-cops) "Incorrect password passed"))
          ((eq? m "withdraw") withdraw)
          ((eq? m "deposit") deposit)
          (else (error "Unknown" m))))
  dispatch)


(define acc (make-account 100 "hola"))

(display (acc "withdraw" "1"))
(display (acc "withdraw" "1"))
(display (acc "withdraw" "1"))
((acc "withdraw" "hola") 40)
((acc "withdraw" "hola") 11)
((acc "withdraw" "hola") 14)
